name: Release PyPI
on:
  push:
    branches:
      - main
    paths:
      - "python/sglang/version.py"
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'reflectionai/sglang'
    runs-on: ubuntu-latest
    environment: "prod"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_ARTIFACT_REGISTRY_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload to pypi
        run: |
          cd python
          cp ../README.md ../LICENSE .
          pip install build
          python3 -m build
          pip install twine
          ACCESS_TOKEN="$(gcloud auth print-access-token)"
          python3 -m twine upload --repository-url https://us-central1-python.pkg.dev/reflectionai/olympus-pypi/ dist/* -u oauth2accesstoken -p "$ACCESS_TOKEN"
